### PR TITLE
Typo "**@odata.nextLink**"→"**\@odata.nextLink**"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
bold with escape characters

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online

### CODE REVIEW

**Comment by daspek** [comment]
Docs Build status updates of commit _[05a45fb](https://github.com/hyoshioka0128/onedrive-api-docs/commits/05a45fbc1d47ef52a056a6218c11b1bc8c5e3745)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/rest-api/api/driveitem_delta.md](https://github.com/hyoshioka0128/onedrive-api-docs/blob/patch-3/docs/rest-api/api/driveitem_delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online&branch=pr-en-us-1166) (>= odsp-graph-online) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C12%5C1b9326b4-eb89-99a2-12be-09cf82b65094%5CPullRequest%5C201910122154036337-1166%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kU9HhSXrhovolDd3A83boPDSMR%2BLglnpwecqwNjH8sY%3D&st=2019-10-12T21%3A50%3A45Z&se=2019-11-12T21%3A55%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Could you please explain a bit more about the reason of PR not being built? Thanks.

**Comment by TinaMcN** [comment]
@chackman this fix has not been published in the English source content
@JeremyKelley is this your content and if so, can you help?

**Comment by chackman** [comment]
> @chackman this fix has not been published in the English source content
> @JeremyKelley is this your content and if so, can you help?

Are you unable to complete the pull request?

**Comment by hyoshioka0128** [comment]
Duplicate #1160 .
Closed #1166 .

**Pull request closed without merging**
