### PR TITLE
Update validationtoken to validationToken

### PR DESCRIPTION
**Pull request by exp0nge**
The endpoint returns `validationToken` with a capital T.

### CODE REVIEW

**Comment by ificator** [comment]
Thanks @exp0nge.

Can you tell us whether you were hitting a business or consumer account when you saw `validationToken` (with a capital T) come back?

**Comment by exp0nge** [comment]
@ificator sorry, consumer account

**Comment by ificator** [comment]
And did you make the subscription via MS Graph or directly to https://api.onedrive.com?

Sorry for all the questions - we have a few places where this can happen and we need them all to be consistent.

**Comment by exp0nge** [comment]
@ificator No problem, I get it. 

The endpoint is: `https://graph.microsoft.com/v1.0/subscriptions`.

**Comment by ificator** [comment]
Thanks @exp0nge!

So the issue is that OneDrive Business and OneDrive Consumer both use `validationtoken`, while Microsoft Graph uses `validationToken`. Since our documentation now is "Graph centric" your change makes sense, but we'll probably want to also update [this page](https://github.com/OneDrive/onedrive-api-docs/blob/master/direct-endpoint-differences.md) to call out that the direct endpoints expect `validationtoken`.

**Pull request closed without merging**
