### PR TITLE
docs: fix MS App Registration Portal links

### LINKED ISSUE #1297: Application registrations portal is no longer available
There is a link to the Application registrations portal which sends me to a page that says this:

Application registrations portal is no longer available to register and manage converged applications. We recommend that ​you manage your existing applications and register new applications by using the App registrations (now Generally Available) experience in the Azure portal. ​

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be99838-ec0d-2d14-954e-4a6cff48096d
* Version Independent ID: bb52ff31-8e3d-122f-edbb-6b1cb3fde806
* Content: [Access OneDrive and SharePoint via Microsoft Graph API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online)
* Content Source: [docs/rest-api/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/index.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

### LINKED ISSUE #1348: Outdated information on app registration docpage
App registration has been moved from the Application Registration Portal to Azure App resistrations for all users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02010cc-2715-86ca-b3fe-e4f92e934fdb
* Version Independent ID: 27b3e16e-f80f-32f4-0e4f-69cfcd1cf769
* Content: [Create an app with Microsoft Graph - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online)
* Content Source: [docs/rest-api/getting-started/app-registration.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/app-registration.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

### LINKED ISSUE #1354: Instructions for registering a new app are incorrect after migration to Azure Portal
Instructions to register app should be modified to reflect the new method through azure portal as current instructions result being presented with the below:

screenshot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02010cc-2715-86ca-b3fe-e4f92e934fdb
* Version Independent ID: 27b3e16e-f80f-32f4-0e4f-69cfcd1cf769
* Content: [Create an app with Microsoft Graph - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online)
* Content Source: [docs/rest-api/getting-started/app-registration.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/app-registration.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

### LINKED ISSUE #1372: Broken link in Getting started > App registration
The link in the [Register your app with Microsoft](https://apps.dev.microsoft.com/?referrer=https%3A%2F%2Fdev.onedrive.com) section might be broken. The page redirects users to an Azure portal page.

> You can no longer manage converged applications here. [Go to the Azure portal.](https://apps.dev.microsoft.com/?referrer=https%3A%2F%2Fdev.onedrive.com#)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02010cc-2715-86ca-b3fe-e4f92e934fdb
* Version Independent ID: 27b3e16e-f80f-32f4-0e4f-69cfcd1cf769
* Content: [Create an app with Microsoft Graph - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online)
* Content Source: [docs/rest-api/getting-started/app-registration.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/app-registration.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

### PR DESCRIPTION
**Pull request by chinmaykunkikar**
Fixes #1297, fixes #1348, fixes #1354, fixes #1372
Improves #1346

- As per a blog entry (https://developer.microsoft.com/en-us/identity/blogs/deprecation-of-app-registrations-legacy-experience-and-the-application-registration-portal-apps-dev-microsoft-com/), Application Registration Portal (apps.dev.microsoft.com) has been fully deprecated since March 2020.
Instead, app registration is unified on Azure App registrations page.

- This commit will fix the existing Application Registration Portal links with Azure Portal links.

- The name 'Azure App registrations page' (come from here: https://docs.microsoft.com/en-us/azure/active-directory/develop/app-registrations-training-guide-for-app-registrations-legacy-users#differences-between-the-application-registration-portal-and-app-registrations-page) will be used instead of 'Microsoft Application Registration Portal'.

### CODE REVIEW

**Review by chackman — APPROVED** [review]
Thank you!

**Comment by chinmaykunkikar** [comment]
@chackman new review was requested accidentally.

**Review by chackman — APPROVED** [review]
No worries, I'll approve again. You should be OK to merge the PR; if not, let us know and we can do it.

**Comment by chinmaykunkikar** [comment]
I don't have write access to the repo so I don't think I'll be able to merge the PR.
Can you do it?

**Comment by chackman** [comment]
Will do.

**Pull request merged**
