### PR TITLE
Use M365 Header

### PR DESCRIPTION
**Pull request by raprice**
Hello, this content needs to use the Microsoft 365 product-level header. Please let me know if you have any questions.
-Rachel, DevRel Information Architect

P.S., If you're wondering "What is a product-level header?" please see:  https://review.docs.microsoft.com/en-us/help/onboard/admin/navigation-product-level-header?branch=main#what-is-product-level-navigation-for

### CODE REVIEW

**Comment by raprice** [comment]
@JeremyKelley Can you please merge this? Thanks!

**Comment by raprice** [comment]
@JeremyKelley Are you able to merge this? Thanks.

**Comment by raprice** [comment]
@patrick-rodgers Are you able to merge this? Thanks.

**Review by patrick-rodgers — APPROVED** [review]

**Comment by patrick-rodgers** [comment]
@raprice - done!

**Pull request merged**
